### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by HStakhiv**
image

### CODE REVIEW

**Comment by HStakhiv** [comment]
Speed without `COUNT`
image

**Review by VadymShkarbul — APPROVED** [review]

**Comment by HStakhiv** [comment]
Run on AMD Ryzen 5 3600
image

**Comment by HStakhiv** [comment]
Found that on faster PC without `COUNT` it works faster
image

**Comment by HStakhiv** [comment]
image

**Review by Nattalli — APPROVED** [review]
Wow, @HStakhiv you made a good job! Your program is so fast 🚀 😲

**Comment by HStakhiv** [comment]
> Wow, @HStakhiv you made a good job! Your program is so fast rocket astonished

Thank you!

**Pull request closed without merging**
