### PR TITLE
the fastest that i found - 44.7

### PR DESCRIPTION
**Pull request by phaishuk**
fastest_one

### CODE REVIEW

**Review by Bohdan-Salamakha — CHANGES_REQUESTED** [review]
don't work on the master branch - it's a bad practice
https://github.com/mate-academy/py-task-guideline/blob/main/README.md#:~:text=git%20checkout%20%2Db%20develop

**Review by Bohdan-Salamakha — CHANGES_REQUESTED** [review]
create a pull request from the develop branch
image

**Comment by phaishuk** [comment]
i've done, man, please check it out
https://github.com/mate-academy/py-brute-force-password/pull/131

**Comment by phaishuk** [comment]
i've done instantly but you dont review it..

**Pull request closed without merging**
